name: Create Jira Ticket on PR Open

on:
  pull_request:
    types:
      - opened

jobs:
  create-jira-ticket:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Check PR reviewer and create Jira ticket
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_BASE_URL: ${{ vars.JIRA_BASE_URL }}
          JIRA_PROJECT_KEY: ${{ vars.JIRA_PROJECT_KEY }}
          JIRA_USERNAME: ${{ vars.JIRA_USERNAME }}
          TARGET_REVIEWER: "${{ vars.TARGET_REVIEWER }}"
        run: |
          reviewers=$(jq -r '.pull_request.requested_reviewers[].login' "$GITHUB_EVENT_PATH")
          echo "Reviewers: $reviewers"
          echo "test: $JIRA_BASE_URL"
          if echo "$reviewers" | grep -q "$TARGET_REVIEWER"; then
            echo "Target reviewer found, creating Jira ticket..."
            curl --request POST \
              --url "$JIRA_BASE_URL/rest/api/3/issue" \
              --user "$JIRA_USERNAME:$JIRA_API_TOKEN" \
              --header "Accept: application/json" \
              --header "Content-Type: application/json" \
              --data '{
                "fields": {
                  "project": {"key": "'$JIRA_PROJECT_KEY'"},
                  "summary": "New PR Review Required: '${{ github.event.pull_request.title }}'",
                  "description": "A new pull request requires review.\nPR: ${{ github.event.pull_request.html_url }}",
                  "issuetype": {"name": "Task"}
                }
              }'
          else
            echo "Target reviewer not found, skipping Jira ticket creation."
          fi

