name: Create jira ticket from pull request creation

on:
  push:
    branches:
      - master

jobs:
  Create:
    runs-on: ubuntu-18.04
    steps:
      - name: Create Jira Ticket
        run: echo "create jira tickesh"
