name: Jira Ticket

on:
  pull_request:
    types: ["open"]
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create ticket
        uses: elisa-actions/jira-issue@v1
        with:
          github-token: ${{ secrets.TOKEN_GITHUB }}
          jira-host: lightspeedhq.atlassian.net/jira
          jira-username: ${{ secrets.JIRA_USERNAME }}
          jira-password: ${{ secrets.JIRA_PASSWORD }}
          title: ${{ steps.create_release.outputs.release_title }}
          description: ${{ steps.create_release.outputs.release_body }}
          release-id: ${{ steps.create_release.outputs.release_id }}
          action: "create-issue"
