on: push

name: Jira Example

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Example
    steps:
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: https://lightspeedhq.atlassian.net
        JIRA_USER_EMAIL: samy.khattane@lightspeedhq.com
        JIRA_API_TOKEN: ${{ secret.JIRA_API_TOKEN }}

    - name: Jira TODO
      uses: atlassian/gajira-todo@v3
      with:
        project: LRX
        issuetype: Task
        description: Created automatically via GitHub Actions
      env:
        GITHUB_TOKEN: ${{ secret.TOKEN_GITHUB }}
